In [2]:
import torch

torch.__version__
print(torch.cuda.device_count())

0


## Creating tensors

- Scalar
- Vector
- Matrix
- Tensor

In [3]:
# 1. scalar
scalar = torch.tensor(7)
print("shape = ", scalar.shape)
print("ndim = ", scalar.ndim)
print("scalar.item() = ", scalar.item())

shape =  torch.Size([])
ndim =  0
scalar.item() =  7


In [4]:
# 2. vector
vector = torch.tensor([7, 7, 8])
print("shape = ", vector.shape)
print("ndim = ", vector.ndim)

shape =  torch.Size([3])
ndim =  1


In [5]:
# 3. MATRIX
MATRIX = torch.tensor([[1, 2, 3],
                      [2, 4, 5]])
print(MATRIX)
print("shape = ", MATRIX.shape)
print("ndim = ", MATRIX.ndim)

tensor([[1, 2, 3],
        [2, 4, 5]])
shape =  torch.Size([2, 3])
ndim =  2


In [6]:
# 4. TENSOR
TENSOR = torch.tensor([[
    [1, 2, 3, 4],
    [3, 6, 9, 12],
    [2, 4, 5, 9] ],
    [[10, 20, 30, 40],
    [30, 60, 90, 120],
    [20, 40, 50, 90]]])
print(TENSOR)
print(TENSOR.shape)
print(TENSOR.ndim) # == number of brackets

tensor([[[  1,   2,   3,   4],
         [  3,   6,   9,  12],
         [  2,   4,   5,   9]],

        [[ 10,  20,  30,  40],
         [ 30,  60,  90, 120],
         [ 20,  40,  50,  90]]])
torch.Size([2, 3, 4])
3


## Random Tensors


In [7]:
# random_tensor = torch.rand(size=(224, 224, 3))
random_tensor = torch.rand(224, 224, 3)
print(random_tensor.dtype)
print(random_tensor.ndim)
print(random_tensor.shape)
print("random_tensor = ", random_tensor)

torch.float32
3
torch.Size([224, 224, 3])
random_tensor =  tensor([[[0.9508, 0.9043, 0.0794],
         [0.8317, 0.6823, 0.9257],
         [0.6547, 0.2828, 0.7742],
         ...,
         [0.4926, 0.4197, 0.9968],
         [0.8876, 0.2612, 0.5143],
         [0.2128, 0.1540, 0.6192]],

        [[0.0630, 0.3973, 0.8786],
         [0.7388, 0.4045, 0.1463],
         [0.5167, 0.5915, 0.4148],
         ...,
         [0.4314, 0.1129, 0.3522],
         [0.2913, 0.5950, 0.4366],
         [0.4573, 0.8633, 0.5080]],

        [[0.7661, 0.3839, 0.2150],
         [0.6799, 0.3416, 0.6575],
         [0.5892, 0.3318, 0.8665],
         ...,
         [0.6566, 0.4546, 0.9109],
         [0.6139, 0.2293, 0.8545],
         [0.9227, 0.4840, 0.5465]],

        ...,

        [[0.2390, 0.1148, 0.6618],
         [0.9858, 0.7771, 0.8654],
         [0.9198, 0.1795, 0.1070],
         ...,
         [0.0662, 0.0331, 0.4291],
         [0.8423, 0.2375, 0.9065],
         [0.0047, 0.8765, 0.1155]],

        [[0.1851, 0.400

## Zeros and ones

In [8]:
zeros = torch.zeros(size=(3, 4))
print(zeros)

ones = torch.ones(3,4)
print(ones)



tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


## Creating a range and tensors like

In [9]:
# zero_to_ten_deprecated = torch.range(0, 10)
# print(zero_to_ten_deprecated)

zeros_to_ten = torch.arange(start=0, end=10, step=1)
print(zeros_to_ten)

ten_zeros = torch.zeros_like(input=zeros_to_ten)
print(ten_zeros)
ten_ones = torch.ones_like(input=zeros_to_ten)
print(ten_ones)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])


## Tensor datatypes

- For precision in computing!
- The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.
- Generally if you see `torch.cuda` anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).
- The most common type (and generally the default) is `torch.float32` or `torch.float`

In [11]:
# For precision in computing!
# The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.
# `torch.float32` or `torch.float`

# Default datatype for tensors is float32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))


# Tensor operations

## Addition
## Substraction
## Multiplication (element-wise)

In [14]:
import torch

tensor = torch.tensor([1, 2, 3])
print(tensor * tensor)
print(torch.mul(tensor, tensor))
print(torch.mul(tensor, tensor))
# Division
print("----Matrix multiplication----")
tensor = torch.tensor([1, 2, 3])
print(torch.matmul(tensor, tensor))
print(tensor @ tensor)


tensor([1, 4, 9])
tensor([1, 4, 9])
tensor([1, 4, 9])
----Matrix multiplication----
tensor(14)
tensor(14)


UsageError: Line magic function `%%time` not found.


In [15]:
%%time

# tensor = torch.tensor([1, 2, 3])
tensor = torch.arange(start=0, end=1000000, step=1)

# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
print(len(tensor))
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value


1000000
CPU times: total: 6.84 s
Wall time: 7.15 s


tensor(333332833333500000)

In [16]:
%%time
torch.matmul(tensor, tensor)


CPU times: total: 0 ns
Wall time: 1 ms


tensor(333332833333500000)

## COMMON ERRORS

## Common issues: mismatch in tensor `shape`, `datatype` and `device`

For example, one of tensors is torch.float32 and the other is torch.float16 (PyTorch often likes tensors to be the same format).

Or one of your tensors is on the CPU and the other is on the GPU (PyTorch likes calculations between tensors to be on the same device).


In [13]:
# Getting information from tensors
print("shape - what shape is the tensor? (some operations require specific shape rules)")
print("dtype - what datatype are the elements within the tensor stored in?")
print("device - what device is the tensor stored on? (usually GPU or CPU)\n")

# Create a tensor
some_tensor = torch.rand(3, 4)

# Find out details about it
print(some_tensor)
print(f"Dimension (ndim) of tensor: {some_tensor.ndim}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

shape - what shape is the tensor? (some operations require specific shape rules)
dtype - what datatype are the elements within the tensor stored in?
device - what device is the tensor stored on? (usually GPU or CPU)

tensor([[0.5328, 0.4264, 0.4994, 0.4024],
        [0.3332, 0.8220, 0.1778, 0.1137],
        [0.4973, 0.1220, 0.7285, 0.7457]])
Dimension (ndim) of tensor: 2
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [11]:
# Shapes need to be in the right way  
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)


RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [12]:
print(torch.matmul(tensor_A, tensor_B.T))
print(torch.mm(tensor_A, tensor_B.T))

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])
tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])



## Neural networks are full of matrix multiplications and dot products.

The `torch.nn.Linear()` module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input x and a weights matrix A.


$y = x \cdot A^T + b$

Try changing the values of in_features and out_features below and see what happens.

In [1]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 

x = torch.tensor([[1, 2],
                [3, 4],
                [5, 6]], dtype=torch.float32)
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

NameError: name 'torch' is not defined


## Finding the min, max, mean, sum, etc (aggregation)

In [23]:
x = torch.arange(0, 100, 10)

print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")


torch.min(x), torch.max(x), torch.mean(x.type(torch.float32)), torch.sum(x)

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


(tensor(0), tensor(90), tensor(45.), tensor(450))

In [24]:
import torch

# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")


Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


In [9]:
import torch

tensor = torch.arange(10, 100, 10)
print("Change tensor datatype")
# Create a tensor and check its datatype
tensor = torch.arange(10., 100., 10.)
print(tensor.dtype)
print(tensor)

# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
print(tensor_float16.dtype)
print(tensor_float16)

# Create a int8 tensor
tensor_int8 = tensor.type(torch.int8)
print(tensor_int8.dtype)
print(tensor_int8)


Change tensor datatype
torch.float32
tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.])
torch.float16
tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)
torch.int8
tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)


## Reshaping, stacking, squeezing and unsqueezing

Method	| One-line description
---|---
`torch.reshape(input, shape)`	| Reshapes input to shape (if compatible), can also use torch.Tensor.reshape().
`Tensor.view(shape)`	|Returns a view of the original tensor in a different shape but shares the same data as the original tensor.
`torch.stack(tensors, dim=0)`	|Concatenates a sequence of tensors along a new dimension (dim), all tensors must be same size.
`torch.squeeze(input)`	|Squeezes input to remove all the dimenions with value 1.
`torch.unsqueeze(input, dim)`	|Returns input with a dimension value of 1 added at dim.
`torch.permute(input, dims)`	|Returns a view of the original input with its dimensions permuted (rearranged) to dims.

In [1]:
import torch

x = torch.arange(0., 10.)
print(x)
print(x.shape)

x_reshaped = x.reshape(10)
print(x_reshaped)
x_reshaped = x.reshape(1, 10)
print(x_reshaped)


tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
torch.Size([10])
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])


## view
A tensor view in PyTorch is a way to create a new tensor that shares the same data as the original tensor but has a different shape or strides.

Views are used to reshape, transpose, or otherwise change the view of the data without copying the underlying data.
This makes operations more memory-efficient and faster.

In [2]:
import torch

print(x)
z = x.view(2, 5)
print(z)

# Changing view (z) changes x
z[:, 0] = 5
z, x


tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
tensor([[0., 1., 2., 3., 4.],
        [5., 6., 7., 8., 9.]])


(tensor([[5., 1., 2., 3., 4.],
         [5., 6., 7., 8., 9.]]),
 tensor([5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]))

## Stack

In [3]:
import torch

# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
print(x_stacked)

x_stacked = torch.stack([x, x, x, x], dim=1)

print(x_stacked)


tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
tensor([[5., 5., 5., 5.],
        [1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


## Squeeze

In [4]:
import torch

# Stack tensors on top of each other
print("---Squeeze---")
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

print("---Unsqueeze---")
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# And to do the reverse of torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.
## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

---Squeeze---
Previous tensor: tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([5., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([10])
---Unsqueeze---
Previous tensor: tensor([5., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([10])

New tensor: tensor([[5., 1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 10])


## Permute

In [5]:
import torch

print("-----Permute-----")
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3))

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

-----Permute-----
Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Sometimes you'll want to select specific data from tensors (for example, only the first column or second row).

In [28]:
# Create a tensor 
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
print("x = ", x)
print("x.shape = ", x.shape)
print("--------")

# Let's index bracket by bracket
print(f"x[0] = First square bracket = {x[0]}") 
print(f"x[0][0] = Second square bracket = {x[0][0]}") 
print(f"x[0][0][0] = Third square bracket = {x[0][0][0]}")

print(x[:, :, 0])

# You can also use : to specify "all values in this dimension" and then use a comma (,) to add another dimension.
# Get all values of 0th dimension and the 0 index of 1st dimension
print(x[:, 0])
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
print(x[:, :, 1])
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
print(x[:, 1, 1])
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension 
print(x[0, 0, :]) # same as x[0][0]

x =  tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
x.shape =  torch.Size([1, 3, 3])
--------
x[0] = First square bracket = tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
x[0][0] = Second square bracket = tensor([1, 2, 3])
x[0][0][0] = Third square bracket = 1
tensor([[1, 4, 7]])
tensor([[1, 2, 3]])
tensor([[2, 5, 8]])
tensor([5])
tensor([1, 2, 3])


## PyTorch tensors & NumPy

In [23]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))